### ISSUE TITLE
Muy buen trabajo!

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/f-m3-evaluacion-intermedia-leireriel#1]
Buen trabajo @leireriel !

Algunas pistas para mejorarlo:

- [x] Utiliza el nombre del Pokemon para el Alt de la imagen
- [x] Usa el `id` de cada pokemon para el  `key` de react cuando mapeas y creas un listado de componentes
- [x] Añade estilos (un archivo sass o css por componente)
- [x] Revisa los metadatos en index.html (lang, title...)

Cuando tengas esto puedes:

1. Mover el array de pokemons a otro archivo e importarlo en App.
2. Inicializar el estado de App con el array de pokemons y utilizar este en lugar de la constante `pokemon`.
3. Añadir un click a Pokemon que: marca o desmarca el pokemon como favorito en el array del estado de App.
4. Pasar este dato al componente Pokemon por props
5. Pintar Pokemon con otros estilos cuando por props nos llegue la info de que el pokemon es favorito

Si tienes cualquier duda, avisa!

Al turrón

**Comment by leireriel** [comment]
Done!
Also added:

- Favs pokemons
- Local Storage for favs
- Input to search pokemons

Thank you @oneeyedman !

**Comment by oneeyedman** [comment]
Super buen trabajo, @leireriel ! MUY BUEN TRABAJO!
